/*
 * generated by Xtext 2.23.0
 */
package ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.validation;

import org.eclipse.xtext.validation.Check;

import ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.Perspective;
import ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.perspectiveDSL.PerspectiveDSLPackage;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class PerspectiveDSLValidator extends AbstractPerspectiveDSLValidator {
	
	public static final String INVALID_NAME = "invalidName";
//
//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital",
//					PerspectiveDSLPackage.Literals.GREETING__NAME,
//					INVALID_NAME);
//		}
//	}
	
	@Check
    public void checkPerspectiveStartsWithCapital(Perspective perspective) {
        if (!Character.isUpperCase(perspective.getName().charAt(0))) {
            warning("Perspective element name should start with a capital",
                    PerspectiveDSLPackage.Literals.PERSPECTIVE__NAME,
                    INVALID_NAME);
        }
    }

//    @Check
//    public void checkLanguageStartsWithCapital(ExternalLanguage language) {
//        if (!Character.isUpperCase(language.getName().charAt(0))) {
//            warning("Language name should start with a capital",
//                    PerspectiveDSLPackage.Literals.LANGUAGE__NAME,
//                    INVALID_NAME);
//        }
//    }

//    @Check
//    public void checkLanguageStartsWithCapital(Perspective perspective) {
//        if (!Character.isUpperCase(perspective.getName().charAt(0))) {
//            warning("Perspective name should start with a capital",
//                    PerspectiveDSLPackage.Literals.LANGUAGE__NAME,
//                    INVALID_NAME);
//        }
//    }
	
}
