/*
 * generated by Xtext 2.23.0
 */
package ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.ide;

import ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.PerspectiveDSLRuntimeModule;
import ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.PerspectiveDSLStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class PerspectiveDSLIdeSetup extends PerspectiveDSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new PerspectiveDSLRuntimeModule(), new PerspectiveDSLIdeModule()));
	}
	
}
