/*
 * generated by Xtext 2.23.0
 */
package ca.mcgill.sel.perspectivedsl.ca.mcgill.sel.ide;


/**
 * Use this class to register ide components.
 */
public class PerspectiveDSLIdeModule extends AbstractPerspectiveDSLIdeModule {
}
