/*
 * generated by Xtext 2.23.0
 */
package ca.mcgill.sel.languagedsl.ca.mcgill.sel.ide;


/**
 * Use this class to register ide components.
 */
public class LanguageDSLIdeModule extends AbstractLanguageDSLIdeModule {
}
