/*
 * generated by Xtext 2.23.0
 */
package ca.mcgill.sel.languagedsl.ca.mcgill.sel.ide;

import ca.mcgill.sel.languagedsl.ca.mcgill.sel.LanguageDSLRuntimeModule;
import ca.mcgill.sel.languagedsl.ca.mcgill.sel.LanguageDSLStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class LanguageDSLIdeSetup extends LanguageDSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new LanguageDSLRuntimeModule(), new LanguageDSLIdeModule()));
	}
	
}
