/*
 * generated by Xtext 2.23.0
 */
package ca.mcgill.sel.perspectivedsl.ca.mcgill.sel;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PerspectiveDSLRuntimeModule extends AbstractPerspectiveDSLRuntimeModule {
}
