/*
 * generated by Xtext 2.23.0
 */
package ca.mcgill.sel.languagedsl.ca.mcgill.sel.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class LanguageDSLUiModule extends AbstractLanguageDSLUiModule {

	public LanguageDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
