/*
 * generated by Xtext 2.23.0
 */
package ca.mcgill.sel.languagedsl.ca.mcgill.sel;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class LanguageDSLStandaloneSetup extends LanguageDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new LanguageDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
